### ISSUE TITLE
Restruturar a pasta SRC

### ISSUE THREAD

**Issue by davidcostadev** [Davidmarquardt/pagode-todo#3]
Acho que vc poderia remover essa pasta src/js move tudo que está dentro de src/js para src, em projetos assim não se usa mais a pasta js, até porque vc colocou estilos dentro da pasta src/js

**Comment by Davidmarquardt** [comment]
Resolvido no commit `
bc0cbc4`

**Comment by davidcostadev** [comment]
#bc0cbc4

**Comment by davidcostadev** [comment]
Mano, falta mover a pasta dos js também essa pasta não tem que existe.
